development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: raptor_development
  pool: 5
  username: root
  password: 7254cgd
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: raptor_test
  pool: 5
  username: root
  password: 7254cgd
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: raptor_production
  pool: 5
  username: root
  password: 7254cgd
  socket: /var/run/mysqld/mysqld.sock

